FROM ruby:3.0.0-alpine

# dependencies
RUN apk add --no-cache \
  git build-base postgresql-dev \
  nodejs npm tzdata

# install recent yarn
RUN npm install -g yarn

# install bundler
# RUN gem install bundler

# config home environment
WORKDIR /app

RUN echo ls -l ./

RUN echo ls -l ./vendor/bundle

COPY Gemfile Gemfile.lock /app/
# COPY /vendor/bundle /app/vendor/bundle
ENV BUNDLE_CACHE_PATH "vendor/bundle"
ENV BUNDLE_PATH "/app/vendor/bundle"
# ENV GEM_HOME "/app/vendor/bundle"

# RUN gem install bundler
RUN bundle install --local
