FROM ruby:3.0.0-alpine

# dependencies
RUN apk add --no-cache \
  git build-base postgresql-dev \
  nodejs npm tzdata

# install recent yarn
RUN npm install -g yarn

# install bundler
RUN gem install bundler

# config home environment
WORKDIR /app

COPY ./Gemfile /app/Gemfile
COPY ./Gemfile.lock /app/Gemfile.lock
COPY vendor/cache /app/vendor/cache
COPY vendor/bundle /app/vendor/bundle

RUN ls /app/vendor/
#RUN gem install bundler
RUN bundle config set --local path vendor/cache
RUN bundle cache
RUN bundle install --local
