name: CI

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      BUNDLE_CACHE_PATH: vendor/bundle
      BUNDLE_PATH: vendor/bundle
    steps:
      - uses: actions/checkout@v2

      - name: Setup cache
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: check files
        run: ls vendor/bundle

      - name: echo
        run: echo $BUNDLE_CACHE_PATH

      - name: bundle package
        run: bundle package

      - name: bundle cache
        run: bundle cache

      - name: check files2
        run: ls vendor

      - name: start server
        run: docker-compose up -d

      - name: lint
        run: docker-compose exec -T boilerplate_server bundle exec rubocop

      - name: test
        run: |
          docker-compose exec -T boilerplate_server bundle exec rspec
